// Fazer um menu de exercicios utilizando o exemplo dado em aula
// Criar um menu, onde é possível executar 6 dos exercícios anteriores.
// Cada exercicio deve ser encapsulado em uma função, e o menu deve executar essas funções.
// O usuário poderá escolher qual exercicio ele quer visualizar.

// O usuário deverá digitar 0 para sair do menu.

let opcao = prompt("Escolha uma opção: \n1 - Imprimir números de 1 a 10 usando FOR \n2 - Imprimir números pares de 1 a 10 usando FOR \n3 - Imprima os números ímpares de 0 a 50 usando FOR \n4 - imprima na tela a tabuada de um número qualquer escolhido pelo usuário até o 10 usando FOR \n5 - Imprimir os primeiros 10 números da sequência de Fibonacci usando FOR \n6 - Imprimir números pares de 0 a 20 usando WHILE")

switch (opcao) {
    case "1";

    console.log("")
}