// // // Exercício 2: Verificação de dia da semana
// // Escreva um programa que solicita ao usuário um
// //  número de 1 a 7 representando um dia da
// // semana e exibe o nome correspondente a esse dia.
// //  Considere que 1 representa segunda-feira,
// // 2 representa terça-feira e assim por diante.

// let diaDaSemana = prompt("Escreva um numero 1 até 7")

// if (diaDaSemana == "1" ) {
//     console.log("Segunda-Feira");
// }

// if (diaDaSemana == "2") {
//     console.log("Terça-Feira");
// }

// if (diaDaSemana == "3") {
//     console.log("Quarta-Feira");
// }

// if (diaDaSemana == "4" ) {
//     console.log("Quinta-Feira");
// }

// if (diaDaSemana == "5") {
//     console.log("Sexta-Feira");
// }

// if (diaDaSemana == "6") {
//     console.log("Sábado");
// }

// if (diaDaSemana == "7") {
//     console.log("Domingo")
// }


