// // // Exercício 4: Notas escolares
// // // Faça um programa que receba 4 notas de um
// // //  aluno, calcule e imprima a média aritmética
// // //   das notas e a mensagem de APROVADO para
// // //  média superior ou igual a 7,0 RECUPERAÇÃO para
// // // notas entre 5.0 e 7,0 ou a mensagem de
// // //  REPROVADO para média inferior a 5,0.

// // let notaAluno1 = parseFloat(prompt("Digite primeiro nota do aluno: "))

// // console.log(notaAluno1)

// // let notaAluno2 = parseFloat(prompt("Digite segundo nota do aluno: "))

// // console.log(notaAluno2)

// // let notaAluno3 = parseFloat(prompt("Digite terceiro nota do aluno: "))

// // console.log(notaAluno3) 

// // let notaAluno4 = parseFloat(prompt("Digite quarto nota do aluno: "))

// // console.log(notaAluno4)

// // // Adição -> num1 + num2
// // // Subtração -> num1 - num2
// // // Multiplicação -> num1 * num2
// // // Divisão -> num1 / num2

// // let notaTotal = notaAluno1 + notaAluno2 + notaAluno3 + notaAluno4
// // alert(notaTotal / 4)

// -----------------------------------------------------------------------------------------

// alert ("Informe ás notas de 0 a 10")

// let nota1 = parseFloat(prompt("Digite a primeira nota: "))
// let nota2 = parseFloat(prompt("Digite a segunda nota: "))
// let nota3 = parseFloat(prompt("Digite a terceira nota: "))
// let nota4 = parseFloat(prompt("Digite a quarta nota: "))

// let media = (nota1 + nota2 + nota3 + nota4) / 4

// console.log(media)

// if (media >= 7) {
//     console.log("Aprovado")

// } else if (media < 7 && media >= 5) {
// console.log("Recuperação")

// } else {
//     console.log ("reprovado")
// }

