// // Exercício 6: Verificação de idade
// // Escreva um programa que solicita o ano de nascimento de uma pessoa e verifica se ela é maior
// // de 18 anos. Exiba uma mensagem indicando se a pessoa é maior de idade ou não.

// let ano = parseFloat(prompt("Digite seu ano de nascimento: "))

// if (ano <= 2006 )
//     alert("maior de idade")

// if (ano > 2006 )
//     alert("menor de idade")

// // ---------------------------------------------------------------------------------------

// let anoNascimento = parseInt(prompt("Informe o ano de nascimento"))

// let anoAtual = new Date().getFullYear;

// let idade = anoAtual - anoNascimento;

// if(idade >= 18) {
//     console.log("Você é maior de idade")
//     console.log("Sua idade é :" + idade)

// } else{
//     console.log("Menor idade")
//     console.log("Sua idade é :" + idade)
// }

