// // Exercício 3: Ímpar ou par
// // Faça um programa que receba um número
// //  do usuário e informe se este número
// //   é par ou ímpar.

// let number = prompt("Digite um numero");
// let total = number % 2;
// if(number % 2 == 0) {
//   alert("Par");
// }
// else {
//     alert("Impar")
// }

// -------------------------------------------------------------------

// let num = parseInt(prompt("Informe um número interno: "))

// if (num%2!==0){
//     console.log("O número informado é par")

// }else {
//     console.log("O número informado é impar")
// }