// FOR
// 4. Faça um programa que imprima na tela a tabuada de um número
// qualquer escolhido pelo usuário até o 10.

// let numero = parseInt(prompt("Digite numero para mostrar tabuada: "));

// if (numero) {

//     console.log("Tabuada do " + numero + ":");

//     for (let umadez = 1; umadez <= 10; umadez++) {

//         let resultado = numero * umadez;

//         console.log(numero + " x " + umadez + " = " + resultado);

//     }
// } 

