// WHILE
// 6. Imprimir números pares de 0 a 20 utilizando o loop while

// for (let numero = 2; numero <= 10; numero += 2) {
//     console.log(numero);
// }

// do (numero => + 2) {
//     console.log(numero)

    
    
// }   while(numero = 20)


// let contador =0;

// while(contador <= 10){
//     console.log(contador);
//     contador+=1
// }

// //do - while -> Loop condicional

// let numero = 0;

// do {

//     numero+=1;
    
// } while (numero < 10);

// do {
    
//     numero+=1;

//     console.log(numero);
    
// } while (numero < 10);

// let numero = 0;

// while (numero <= 20) {
//   if (numero % 2 === 0) {
//     console.log(numero);
//   }
//   numero++
// }
